---
# tasks file for sshebableMODT
- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "yes" }
    - { key: "PrintMotd", value: "yes" } 
  notify:
    - restart sshd
